Wwwision:
  Likes:
    eventMetadata:
      # enable tracking of absolute HTTP request URL
      url: true
      # enable tracking of HTTP request Method (GET, POST, ...)
      method: true
      # enable tracking of users IP address
      clientIpAddress: true
      # enable tracking of browsers "userAgent" header
      userAgent: true

Neos:
  EventSourcing:
    EventStore:
      stores:
        'Wwwision.Likes:EventStore':
          storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
          listeners:
            'Wwwision\Likes\.*': true
